apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: prod
description: prod environment
requireApproval: true
gke:
  cluster: projects/arched-envelope-432818-f6/locations/us-central1/clusters/cluster-2

